### ISSUE TITLE
Support RSS feeds by generating data in Atom format

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#77]
## Description

We want to maintain an `index.xml` equivalent of https://kubernetes.io/docs/reference/issues-security/official-cve-feed/index.json
so folks can subscribe to the auto-refreshing CVE feed when a new CVE comes up.

## Details

We can use the kubernetes blog RSS feed to get started as an example: 
* Feed: kubernetes.io/feed.xml
* Code: https://github.com/kubernetes/website/blob/main/layouts/index.rss.xml 

The CVE feed items can be iterated similar to how it is done for `index.json`

Hugo RSS generator: https://gohugo.io/templates/rss/ 

## Testing / Validation

https://validator.w3.org/feed/#validate_by_input

**Comment by mtardy** [comment]
Ok, I can do this, I just spent one hour wondering why no `index.xml` appeared and it was just because the Kubernetes website had [the good idea to rename the default `index` to `feed`](https://github.com/kubernetes/website/blob/6d47deef83776d787f26a594b3a51e7dc0781887/config.toml#L100-L102) for RSS in the global config 🙃

/assign

**Comment by sftim** [comment]
/triage accepted
(why not?)
