### ISSUE TITLE
Move artifacts from k/community to k/sig-security

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/sig-security#9]
**What?**

Create the following set of directory structure:

`k/sig-security`:
- `sig-security-docs`:
   - Refactor this to here: https://github.com/kubernetes/community/blob/master/sig-security/sig-security-docs/OWNERS
- `sig-security-external-audit`:
   - Move all of this here: https://github.com/kubernetes/community/tree/master/sig-security/sig-security-external-audit
   - Move all of this here: https://github.com/kubernetes/community/tree/master/sig-security/security-audit-2019
   - Move all of this here: https://github.com/kubernetes/community/tree/master/sig-security/security-audit-2021
- `sig-security-tooling`:
   - Move this to here: https://github.com/kubernetes/community/blob/master/sig-security/sig-security-tooling/OWNERS

**How?**
This will need two set of PRs, one to remove stuff from `k/community` and one to add the same stuff to `k/sig-security`

**Why do this?**
This will unblock following PRs: https://github.com/kubernetes/community/pull/6140 and https://github.com/kubernetes/community/pull/5853. More importantly, it will allow allow sig-security artifacts to have a single landing page. 

Anything else you would like to add @tabbysable @IanColdwater @reylejano @savitharaghunathan ?

/sig security 
/kind cleanup
/label good first issue
/label help wanted

**Comment by tabbysable** [comment]
@PushkarJ when I was reviewing https://github.com/kubernetes/sig-security/pull/12 I asked for the directory structure to be matched to the old one from `k/community`, but I see here you requested it specifically.

I think that because our subproject names are fairly general terms on their own (`docs` and `tooling` especially) that it could be a little misleading to have the directory names as just those short words. So, I like the old names that match the slack channel names better. I don't want to dictate that, though-- WDYT about this idea of keeping the directory names the same as before?

**Comment by PushkarJ** [comment]
Hi Tabby, thank you for reviewing!! I did not think about mapping the directory names to channel names for consistency earlier but I like the idea. Changed the original description as per your suggestion now. 

@chetak123 please go ahead and make the renaming changes @tabbysable suggested in the PR for adding new files and then we should be good to go

**Comment by PushkarJ** [comment]
With https://github.com/kubernetes/sig-security/pull/12 and https://github.com/kubernetes/community/pull/6176 merged, closing this ticket. Thank you again @chetak123 for working on this!!
